version: '3.8'

services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/quiz_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
  mysqldb:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: quiz_database
      MYSQL_ROOT_PASSWORD: pass



