name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t spring-boot-app .
          docker tag spring-boot-app ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:latest

      - name: Deploy to Vercel
        uses: vercel/vercel-action@v20
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          orgId: ${{ secrets.VERCEL_ORG_ID }}
          projectId: ${{ secrets.VERCEL_PROJECT_ID }}
          vercelToken: ${{ secrets.VERCEL_TOKEN }}