name: Deploy to Render

on:
  push:
    branches:
      - main  # Workflow uruchomi się przy pushu na gałąź 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Używamy najnowszego obrazu Ubuntu do uruchomienia zadań

    steps:
      # 1. Sprawdzenie kodu z repozytorium
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Ustawienie JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # 3. Instalacja zależności i kompilacja aplikacji
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # 4. Deploy na Render
      - name: Deploy to Render
        run: |
          curl -sL https://cli.render.com/install | bash
          export RENDER_API_KEY=${{ secrets.RENDER_API_KEY }}
          render deploy --service quiz-backend